# Auto-generated by Bazelify. Do not modify by hand.

# Include the Dart language extensions to Bazel.
#git_repository(
#    name = "io_bazel_rules_dart",
#    remote = "https://github.com/dart-lang/rules_dart",
#    #tag = "0.0.0-alpha",
#    commit = "258ee60e12536e727aa399835d89afb3fbe367ae",
#)

new_local_repository(
  name = "io_bazel_rules_dart",
  build_file_content = "",
  path = "../rules_dart",
)

load(
    "@io_bazel_rules_dart//dart/build_rules:repositories.bzl",
    "dart_repositories",
)
dart_repositories()

load(
    "@io_bazel_rules_dart//dart/build_rules:pub.bzl",
    "pub_repositories",
)
pub_repositories()


# Include packages defined in pubspec.yaml.
load("//:packages.bzl", "bazelify")
bazelify()
